# This is a basic workflow to help you get started with Actions

# name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [1,2]
        os: [3,4]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: generate_number
        run: |
          echo ${{ matrix.node }}
          echo ${{ matrix.os }}
          echo "::set-output name=random_number::${{ matrix.os }}_${{ matrix.node }}"
  read:
    runs-on: ubuntu-latest
    needs: build
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{ steps.generate_number.outputs.random_number }}
          
